--------------------------------------------------------
--  파일이 생성됨 - 금요일-2월-23-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCUSE
--------------------------------------------------------
CREATE TABLE "BF"."ACCUSE" (
  "NUM" NUMBER(8, 0), 
  "ID" VARCHAR2(40 CHAR), 
  "ACCUSE_NUM" NUMBER(8, 0), 
  "REVIEW_NUM" NUMBER(8, 0), 
  "WRITE_DATE" DATE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table ACCUSE_CATE
--------------------------------------------------------
CREATE TABLE "BF"."ACCUSE_CATE" (
  "NUM" NUMBER(8, 0), 
  "DESCRIPTION" VARCHAR2(40 CHAR)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table AUTHOR
--------------------------------------------------------
CREATE TABLE "BF"."AUTHOR" (
  "NUM" NUMBER(8, 0), 
  "NAME" VARCHAR2(100 CHAR), 
  "COUNTRY_NUM" VARCHAR2(4 BYTE), 
  "BIRTHDAY" VARCHAR2(2000 CHAR), 
  "EDUCATION" VARCHAR2(2000 BYTE), 
  "CAREER" VARCHAR2(2000 BYTE), 
  "DEBUT" VARCHAR2(2000 CHAR), 
  "LINK" VARCHAR2(2000 CHAR), 
  "UPDATE_DATE" DATE, 
  "AWARDS" VARCHAR2(3000 CHAR), 
  "DESCRIBE" CLOB
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS" LOB ("DESCRIBE") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE LOGGING STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
);
--------------------------------------------------------
--  DDL for Table AUTHOREDIT
--------------------------------------------------------
CREATE TABLE "BF"."AUTHOREDIT" (
  "NUM" NUMBER(8, 0), 
  "AUTHOR_NUM" NUMBER(8, 0), 
  "CONTENT" VARCHAR2(4000 BYTE), 
  "CONDITION" VARCHAR2(100 BYTE), 
  "WRITE_DATE" DATE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table BOARD_CONTACT
--------------------------------------------------------
CREATE TABLE "BF"."BOARD_CONTACT" (
  "NUM" NUMBER(8, 0), 
  "TITLE" VARCHAR2(50 CHAR), 
  "CONTENT" VARCHAR2(2000 CHAR), 
  "ID" VARCHAR2(40 CHAR), 
  "WRITE_DATE" DATE, 
  "CATEGORY" NUMBER(8, 0), 
  "REPLY_CONTENT" VARCHAR2(2000 CHAR), 
  "REPLY_CHECK" VARCHAR2(10 CHAR), 
  "FILE_NAME" VARCHAR2(100 CHAR), 
  "FILE_SIZE" NUMBER(8, 0), 
  "FILE_PATH" VARCHAR2(200 CHAR), 
  "REPLY_DATE" DATE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table BOARD_FREQUENCY
--------------------------------------------------------
CREATE TABLE "BF"."BOARD_FREQUENCY" (
  "NUM" NUMBER(8, 0), 
  "TITLE" VARCHAR2(40 CHAR), 
  "CATEGORY" NUMBER(8, 0), 
  "CONTENT" VARCHAR2(2000 CHAR), 
  "WRITE_DATE" DATE DEFAULT SYSDATE, 
  "FILE_NAME" VARCHAR2(100 CHAR), 
  "FILE_SIZE" NUMBER(8, 0), 
  "FILE_PATH" VARCHAR2(200 CHAR)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table BOOK_CATEGORY
--------------------------------------------------------
CREATE TABLE "BF"."BOOK_CATEGORY" (
  "NUM" NUMBER(8, 0), 
  "BOOK_NUM" NUMBER(8, 0), 
  "CATE1_NUM" NUMBER(4, 0), 
  "CATE2_NUM" NUMBER(4, 0), 
  "CATE3_NUM" NUMBER(4, 0)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table BOOK_LIST
--------------------------------------------------------
CREATE TABLE "BF"."BOOK_LIST" (
  "NUM" NUMBER(8, 0), 
  "ID" VARCHAR2(40 CHAR), 
  "BOOK_NUM" NUMBER(8, 0), 
  "PAY_DATE" DATE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table BOOKM
--------------------------------------------------------
CREATE TABLE "BF"."BOOKM" (
  "BOOK_NUM" NUMBER(8, 0), 
  "NAME" VARCHAR2(150 CHAR), 
  "WRITE_DATE" VARCHAR2(1000 BYTE), 
  "PUB_NUM" NUMBER(8, 0), 
  "AUTHOR_NUM" NUMBER(8, 0), 
  "ILLUSTRATOR_NUM" NUMBER(8, 0), 
  "TRANSLATOR_NUM" NUMBER(8, 0), 
  "PRICE" NUMBER(8, 0), 
  "SUPPORT" VARCHAR2(100 BYTE), 
  "IMG_PATH" VARCHAR2(200 BYTE), 
  "FILE_PATH" VARCHAR2(200 BYTE), 
  "FILE_NAME" VARCHAR2(100 BYTE), 
  "FILE_SIZE" NUMBER(8, 0), 
  "PREFERENCE" NUMBER(8, 0), 
  "SERIES_NUM" NUMBER(8, 0), 
  "SUB_TITLE" VARCHAR2(2000 CHAR), 
  "DISCOUNT" NUMBER(4, 2), 
  "DISCOUNT2" NUMBER(4, 2), 
  "TYPE" VARCHAR2(200 BYTE), 
  "INTRO" CLOB, 
  "PUB_INTRO" CLOB, 
  "RENTAL_PERIOD" VARCHAR2(200 BYTE), 
  "RENTAL_PRICE" NUMBER(8, 0)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS" LOB ("INTRO") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE LOGGING STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
) LOB ("PUB_INTRO") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE LOGGING STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
);
--------------------------------------------------------
--  DDL for Table CART_WISH
--------------------------------------------------------
CREATE TABLE "BF"."CART_WISH" (
  "NUM" NUMBER(8, 0), 
  "ID" VARCHAR2(40 CHAR), 
  "BOOK_NUM" NUMBER(8, 0), 
  "CART_WISH" VARCHAR2(20 BYTE)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table CASH_CHARGE
--------------------------------------------------------
CREATE TABLE "BF"."CASH_CHARGE" (
  "NUM" NUMBER(8, 0), 
  "ID" VARCHAR2(40 CHAR), 
  "CHARGE_CASH" NUMBER(8, 0), 
  "POINT_NUM" NUMBER(8, 0), 
  "CHARGE_TYPE_NUM" NUMBER(8, 0), 
  "CHARGE_DATE" DATE DEFAULT SYSDATE, 
  "CASH_TYPE" VARCHAR2(50 BYTE), 
  "ORDER_NUM" NUMBER(16, 0), 
  "TOTAL" NUMBER
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table CASH_CHARGE_MENU
--------------------------------------------------------
CREATE TABLE "BF"."CASH_CHARGE_MENU" (
  "NUM" NUMBER(8, 0), 
  "ID" NUMBER(8, 0), 
  "CHARGE_CASH" NUMBER(8, 0), 
  "PERCENTAGE" NUMBER(4, 0)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table CASH_CHARGE_TYPE
--------------------------------------------------------
CREATE TABLE "BF"."CASH_CHARGE_TYPE" (
  "NUM" NUMBER(8, 0), 
  "CHARGE_TYPE" VARCHAR2(40 CHAR)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table COUNTRY
--------------------------------------------------------
CREATE TABLE "BF"."COUNTRY" (
  "COUNTRY_NUM" VARCHAR2(4 BYTE), 
  "COUNTRY_NAME" VARCHAR2(50 BYTE), 
  "COUNTRY_EN" VARCHAR2(50 BYTE)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table FIRST_CATE
--------------------------------------------------------
CREATE TABLE "BF"."FIRST_CATE" (
  "NUM" NUMBER(4, 0), 
  "NAME" VARCHAR2(40 BYTE)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table KEYWORD
--------------------------------------------------------
CREATE TABLE "BF"."KEYWORD" (
  "NUM" NUMBER(8, 0), 
  "NAME" VARCHAR2(100 CHAR)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table KEYWORD_LIST
--------------------------------------------------------
CREATE TABLE "BF"."KEYWORD_LIST" (
  "NUM" NUMBER(8, 0), 
  "KEYWORD_NUM" NUMBER(8, 0), 
  "BOOK_NUM" NUMBER(8, 0)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------
CREATE TABLE "BF"."MEMBER" (
  "NUM" NUMBER(8, 0), 
  "ID" VARCHAR2(40 CHAR), 
  "PASSWORD" VARCHAR2(40 CHAR), 
  "EMAIL" VARCHAR2(30 CHAR), 
  "GENDER" VARCHAR2(10 CHAR), 
  "REGISTER_DATE" DATE DEFAULT SYSDATE, 
  "BIRTHDAY" DATE, 
  "MARKETING_CHECK" VARCHAR2(5 CHAR), 
  "IP" VARCHAR2(40 CHAR), 
  "LAST_JOIN" DATE DEFAULT SYSDATE, 
  "PHONE" VARCHAR2(50 BYTE), 
  "ROLE" VARCHAR2(20 BYTE) DEFAULT 'ROLE_USER', 
  "NAME" VARCHAR2(40 BYTE)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------
CREATE TABLE "BF"."NOTICE" (
  "NUM" NUMBER(8, 0), 
  "ID" VARCHAR2(40 CHAR), 
  "TITLE" VARCHAR2(60 CHAR), 
  "WRITE_DATE" DATE DEFAULT SYSDATE, 
  "CONTENT" CLOB
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS" LOB ("CONTENT") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE LOGGING STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
);
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------
CREATE TABLE "BF"."PAYMENT" (
  "NUM" NUMBER(8, 0), 
  "ORDER_NUM" NUMBER(16, 0), 
  "BOOK_NUM" NUMBER(8, 0), 
  "PRICE" NUMBER(8, 0), 
  "PAYMENT_DATE" DATE, 
  "PRESENT_CHECK" VARCHAR2(5 BYTE), 
  "CANCEL_CHECK" VARCHAR2(5 BYTE), 
  "FREE_PASS" VARCHAR2(5 BYTE), 
  "ID" VARCHAR2(40 CHAR), 
  "PAY_TYPE" VARCHAR2(50 BYTE), 
  "POINT_USE" NUMBER(8, 0) DEFAULT 0, 
  "CASH_USE" NUMBER(8, 0) DEFAULT 0, 
  "RENTAL_DATE" DATE DEFAULT SYSDATE + 5, 
  "RENTAL_STATE" VARCHAR2(20 BYTE), 
  "STATE" VARCHAR2(20 BYTE) DEFAULT 'yes'
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table POINT
--------------------------------------------------------
CREATE TABLE "BF"."POINT" (
  "NUM" NUMBER(8, 0), 
  "ID" VARCHAR2(40 CHAR), 
  "POINT" NUMBER(8, 0), 
  "POINT_TYPE" VARCHAR2(50 CHAR), 
  "CHARGE_DATE" DATE DEFAULT SYSDATE, 
  "DESTORY_DATE" DATE DEFAULT SYSDATE + 30, 
  "STATE" VARCHAR2(30 CHAR), 
  "REMAIN" NUMBER(8, 0) DEFAULT 0
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table PREFERENCE
--------------------------------------------------------
CREATE TABLE "BF"."PREFERENCE" (
  "NUM" NUMBER(8, 0), 
  "ID" VARCHAR2(40 CHAR), 
  "AUTHOR_NUM" NUMBER(8, 0), 
  "SERIES_NUM" NUMBER(8, 0)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table PUBLISHER
--------------------------------------------------------
CREATE TABLE "BF"."PUBLISHER" (
  "PUB_NUM" NUMBER(8, 0), 
  "NAME" VARCHAR2(100 BYTE), 
  "URL" VARCHAR2(100 BYTE), 
  "JOIN_DATE" DATE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table QNA_CATE1
--------------------------------------------------------
CREATE TABLE "BF"."QNA_CATE1" (
  "NUM" NUMBER(8, 0), 
  "NAME" VARCHAR2(40 CHAR)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table QNA_CATE2
--------------------------------------------------------
CREATE TABLE "BF"."QNA_CATE2" (
  "NUM" NUMBER(8, 0), 
  "NAME" VARCHAR2(40 CHAR), 
  "CATE1_NUM" NUMBER(8, 0)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table RECENT_LOOKBOOK
--------------------------------------------------------
  CREATE TABLE "BF"."RECENT_LOOKBOOK" 
   (	"NUM" NUMBER(8,0), 
	"ID" VARCHAR2(40 CHAR), 
	"BOOK_NUM" NUMBER(8,0), 
	"LOOK_DATE" DATE DEFAULT SYSDATE, 
	"DESTROY_DATE" DATE DEFAULT SYSDATE+14, 
	 PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "RECENT_LOOKBOOK_ID_FK" FOREIGN KEY ("ID")
	  REFERENCES "BF"."MEMBER" ("ID") ENABLE, 
	 CONSTRAINT "RECENT_LOOKBOOK_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM")
	  REFERENCES "BF"."BOOKM" ("BOOK_NUM") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------
CREATE TABLE "BF"."REVIEW" (
  "NUM" NUMBER(8, 0), 
  "ID" VARCHAR2(40 CHAR), 
  "BOOK_NUM" NUMBER(8, 0), 
  "CONTENT" VARCHAR2(4000 BYTE), 
  "WRITE_DATE" DATE DEFAULT SYSDATE, 
  "STAR_POINT" NUMBER(3, 0), 
  "SPOILER" VARCHAR2(20 CHAR), 
  "PREFERENCE" NUMBER(8, 0) DEFAULT 0, 
  "DISPLAY" VARCHAR2(20 CHAR)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table REVIEW_REPLY
--------------------------------------------------------
CREATE TABLE "BF"."REVIEW_REPLY" (
  "NUM" NUMBER(8, 0), 
  "ID" VARCHAR2(40 CHAR), 
  "CONTENT" VARCHAR2(4000 BYTE), 
  "WRITE_DATE" DATE DEFAULT SYSDATE, 
  "REVIEW_NUM" NUMBER(8, 0)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table SECOND_CATE
--------------------------------------------------------
CREATE TABLE "BF"."SECOND_CATE" (
  "NUM" NUMBER(4, 0), 
  "NAME" VARCHAR2(40 BYTE), 
  "FIRST_CATE" NUMBER(4, 0)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table SERIES
--------------------------------------------------------
CREATE TABLE "BF"."SERIES" (
  "NUM" NUMBER(8, 0), 
  "NAME" VARCHAR2(200 CHAR)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table THIRD_CATE
--------------------------------------------------------
CREATE TABLE "BF"."THIRD_CATE" (
  "NUM" NUMBER(4, 0), 
  "NAME" VARCHAR2(40 BYTE), 
  "SECOND_CATE" NUMBER(4, 0)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Table BOOK_CONTACT
--------------------------------------------------------
CREATE TABLE "BF"."BOOK_CONTACT" 
(	"NUM" NUMBER(8,0), 
"CATEGORY" NUMBER(8,0), 
"BOOK_NAME" VARCHAR2(200 BYTE), 
"BOOK_WRITER" VARCHAR2(50 BYTE), 
"PUBLISHER" VARCHAR2(50 BYTE), 
"WRITE_DATE" DATE, 
"ID" VARCHAR2(40 CHAR), 
CONSTRAINT "BOOK_CONTACT_FK1" FOREIGN KEY ("ID")
REFERENCES "BF"."MEMBER" ("ID") ON DELETE CASCADE ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index SYS_C004374
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004374" ON "BF"."ACCUSE" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004373
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004373" ON "BF"."ACCUSE_CATE" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004343
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004343" ON "BF"."AUTHOR" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004345
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004345" ON "BF"."AUTHOREDIT" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004332
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004332" ON "BF"."BOARD_CONTACT" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004328
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004328" ON "BF"."BOARD_FREQUENCY" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004386
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004386" ON "BF"."BOOK_CATEGORY" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004397
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004397" ON "BF"."BOOK_LIST" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004352
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004352" ON "BF"."BOOKM" ("BOOK_NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004394
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004394" ON "BF"."CART_WISH" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004317
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004317" ON "BF"."CASH_CHARGE" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index CASH_CHARGE_ORDER_NUM_UK
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."CASH_CHARGE_ORDER_NUM_UK" ON "BF"."CASH_CHARGE" ("ORDER_NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004410
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004410" ON "BF"."CASH_CHARGE_MENU" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004411
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004411" ON "BF"."CASH_CHARGE_MENU" ("ID") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004315
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004315" ON "BF"."CASH_CHARGE_TYPE" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004339
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004339" ON "BF"."COUNTRY" ("COUNTRY_NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004378
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004378" ON "BF"."FIRST_CATE" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004435
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004435" ON "BF"."KEYWORD" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004436
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004436" ON "BF"."KEYWORD_LIST" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004308
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004308" ON "BF"."MEMBER" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004309
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004309" ON "BF"."MEMBER" ("ID") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004420
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004420" ON "BF"."NOTICE" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004361
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004361" ON "BF"."PAYMENT" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004312
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004312" ON "BF"."POINT" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004403
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004403" ON "BF"."PREFERENCE" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004348
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004348" ON "BF"."PUBLISHER" ("PUB_NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004322
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004322" ON "BF"."QNA_CATE1" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004324
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004324" ON "BF"."QNA_CATE2" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004400
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004400" ON "BF"."RECENT_LOOKBOOK" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004366
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004366" ON "BF"."REVIEW" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004369
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004369" ON "BF"."REVIEW_REPLY" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004380
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004380" ON "BF"."SECOND_CATE" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004336
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004336" ON "BF"."SERIES" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  DDL for Index SYS_C004383
--------------------------------------------------------
CREATE UNIQUE INDEX "BF"."SYS_C004383" ON "BF"."THIRD_CATE" ("NUM") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) TABLESPACE "USERS";
--------------------------------------------------------
--  Constraints for Table ACCUSE
--------------------------------------------------------
ALTER TABLE 
  "BF"."ACCUSE" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table ACCUSE_CATE
--------------------------------------------------------
ALTER TABLE 
  "BF"."ACCUSE_CATE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."ACCUSE_CATE" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTHOR
--------------------------------------------------------
ALTER TABLE 
  "BF"."AUTHOR" MODIFY ("NAME" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."AUTHOR" MODIFY ("COUNTRY_NUM" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."AUTHOR" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."AUTHOR" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTHOREDIT
--------------------------------------------------------
ALTER TABLE 
  "BF"."AUTHOREDIT" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD_CONTACT
--------------------------------------------------------
ALTER TABLE 
  "BF"."BOARD_CONTACT" MODIFY ("TITLE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."BOARD_CONTACT" MODIFY ("CONTENT" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."BOARD_CONTACT" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD_FREQUENCY
--------------------------------------------------------
ALTER TABLE 
  "BF"."BOARD_FREQUENCY" MODIFY ("TITLE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."BOARD_FREQUENCY" MODIFY ("CONTENT" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."BOARD_FREQUENCY" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOK_CATEGORY
--------------------------------------------------------
ALTER TABLE 
  "BF"."BOOK_CATEGORY" MODIFY ("BOOK_NUM" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."BOOK_CATEGORY" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOK_LIST
--------------------------------------------------------
ALTER TABLE 
  "BF"."BOOK_LIST" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOKM
--------------------------------------------------------
ALTER TABLE 
  "BF"."BOOKM" MODIFY ("NAME" NOT NULL DISABLE);
ALTER TABLE 
  "BF"."BOOKM" MODIFY ("WRITE_DATE" NOT NULL DISABLE);
ALTER TABLE 
  "BF"."BOOKM" MODIFY ("PRICE" NOT NULL DISABLE);
ALTER TABLE 
  "BF"."BOOKM" 
ADD 
  PRIMARY KEY ("BOOK_NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table CART_WISH
--------------------------------------------------------
ALTER TABLE 
  "BF"."CART_WISH" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table CASH_CHARGE
--------------------------------------------------------
ALTER TABLE 
  "BF"."CASH_CHARGE" 
ADD 
  CONSTRAINT "CASH_CHARGE_ORDER_NUM_UK" UNIQUE ("ORDER_NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "BF"."CASH_CHARGE" MODIFY ("CHARGE_CASH" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."CASH_CHARGE" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "BF"."CASH_CHARGE" MODIFY ("CASH_TYPE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."CASH_CHARGE" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CASH_CHARGE_MENU
--------------------------------------------------------
ALTER TABLE 
  "BF"."CASH_CHARGE_MENU" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."CASH_CHARGE_MENU" MODIFY ("CHARGE_CASH" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."CASH_CHARGE_MENU" MODIFY ("PERCENTAGE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."CASH_CHARGE_MENU" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "BF"."CASH_CHARGE_MENU" 
ADD 
  UNIQUE ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table CASH_CHARGE_TYPE
--------------------------------------------------------
ALTER TABLE 
  "BF"."CASH_CHARGE_TYPE" MODIFY ("CHARGE_TYPE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."CASH_CHARGE_TYPE" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table COUNTRY
--------------------------------------------------------
ALTER TABLE 
  "BF"."COUNTRY" MODIFY ("COUNTRY_NAME" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."COUNTRY" MODIFY ("COUNTRY_EN" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."COUNTRY" 
ADD 
  PRIMARY KEY ("COUNTRY_NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table FIRST_CATE
--------------------------------------------------------
ALTER TABLE 
  "BF"."FIRST_CATE" MODIFY ("NAME" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."FIRST_CATE" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table KEYWORD
--------------------------------------------------------
ALTER TABLE 
  "BF"."KEYWORD" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table KEYWORD_LIST
--------------------------------------------------------
ALTER TABLE 
  "BF"."KEYWORD_LIST" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "BF"."KEYWORD_LIST" MODIFY ("KEYWORD_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------
ALTER TABLE 
  "BF"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."MEMBER" MODIFY ("GENDER" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."MEMBER" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."MEMBER" MODIFY ("ROLE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."MEMBER" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "BF"."MEMBER" 
ADD 
  UNIQUE ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "BF"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------
ALTER TABLE 
  "BF"."NOTICE" MODIFY ("TITLE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."NOTICE" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------
ALTER TABLE 
  "BF"."PAYMENT" MODIFY ("ORDER_NUM" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."PAYMENT" MODIFY ("PRICE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."PAYMENT" MODIFY ("PAYMENT_DATE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."PAYMENT" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "BF"."PAYMENT" MODIFY ("POINT_USE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."PAYMENT" MODIFY ("CASH_USE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."PAYMENT" MODIFY ("RENTAL_DATE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."PAYMENT" MODIFY ("STATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POINT
--------------------------------------------------------
ALTER TABLE 
  "BF"."POINT" MODIFY ("POINT" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."POINT" MODIFY ("POINT_TYPE" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."POINT" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
ALTER TABLE 
  "BF"."POINT" MODIFY ("REMAIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREFERENCE
--------------------------------------------------------
ALTER TABLE 
  "BF"."PREFERENCE" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table PUBLISHER
--------------------------------------------------------
ALTER TABLE 
  "BF"."PUBLISHER" MODIFY ("NAME" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."PUBLISHER" 
ADD 
  PRIMARY KEY ("PUB_NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table QNA_CATE1
--------------------------------------------------------
ALTER TABLE 
  "BF"."QNA_CATE1" MODIFY ("NAME" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."QNA_CATE1" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table QNA_CATE2
--------------------------------------------------------
ALTER TABLE 
  "BF"."QNA_CATE2" MODIFY ("NAME" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."QNA_CATE2" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table RECENT_LOOKBOOK
--------------------------------------------------------
ALTER TABLE 
  "BF"."RECENT_LOOKBOOK" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------
ALTER TABLE 
  "BF"."REVIEW" MODIFY ("STAR_POINT" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."REVIEW" MODIFY ("SPOILER" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."REVIEW" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW_REPLY
--------------------------------------------------------
ALTER TABLE 
  "BF"."REVIEW_REPLY" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table SECOND_CATE
--------------------------------------------------------
ALTER TABLE 
  "BF"."SECOND_CATE" MODIFY ("NAME" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."SECOND_CATE" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table SERIES
--------------------------------------------------------
ALTER TABLE 
  "BF"."SERIES" MODIFY ("NAME" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."SERIES" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Constraints for Table THIRD_CATE
--------------------------------------------------------
ALTER TABLE 
  "BF"."THIRD_CATE" MODIFY ("NAME" NOT NULL ENABLE);
ALTER TABLE 
  "BF"."THIRD_CATE" 
ADD 
  PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) TABLESPACE "USERS" ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCUSE
--------------------------------------------------------
ALTER TABLE 
  "BF"."ACCUSE" 
ADD 
  CONSTRAINT "ACCUSE_ACCUSE_NUM_FK" FOREIGN KEY ("ACCUSE_NUM") REFERENCES "BF"."ACCUSE_CATE" ("NUM") ENABLE;
ALTER TABLE 
  "BF"."ACCUSE" 
ADD 
  CONSTRAINT "REVIEW_REVIEW_NUM_FK" FOREIGN KEY ("REVIEW_NUM") REFERENCES "BF"."REVIEW" ("NUM") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTHOR
--------------------------------------------------------
ALTER TABLE 
  "BF"."AUTHOR" 
ADD 
  CONSTRAINT "COUNTRY_NUM_FK" FOREIGN KEY ("COUNTRY_NUM") REFERENCES "BF"."COUNTRY" ("COUNTRY_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTHOREDIT
--------------------------------------------------------
ALTER TABLE 
  "BF"."AUTHOREDIT" 
ADD 
  CONSTRAINT "AUTHOREDIT_AUTHOR_NUM_FK" FOREIGN KEY ("AUTHOR_NUM") REFERENCES "BF"."AUTHOR" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_CONTACT
--------------------------------------------------------
ALTER TABLE 
  "BF"."BOARD_CONTACT" 
ADD 
  CONSTRAINT "BOARD_CONTACT_CATEGORY_FK" FOREIGN KEY ("CATEGORY") REFERENCES "BF"."QNA_CATE2" ("NUM") ENABLE;
ALTER TABLE 
  "BF"."BOARD_CONTACT" 
ADD 
  CONSTRAINT "BOARD_CONTACT_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_FREQUENCY
--------------------------------------------------------
ALTER TABLE 
  "BF"."BOARD_FREQUENCY" 
ADD 
  CONSTRAINT "BOARD_FREQUENCY_CATEGORY_FK" FOREIGN KEY ("CATEGORY") REFERENCES "BF"."QNA_CATE2" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOK_CATEGORY
--------------------------------------------------------
ALTER TABLE 
  "BF"."BOOK_CATEGORY" 
ADD 
  CONSTRAINT "BOOK_CATEGORY_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ON DELETE CASCADE ENABLE;
ALTER TABLE 
  "BF"."BOOK_CATEGORY" 
ADD 
  CONSTRAINT "BOOK_CATEGORY_CATE1_NUM_FK" FOREIGN KEY ("CATE1_NUM") REFERENCES "BF"."FIRST_CATE" ("NUM") ENABLE;
ALTER TABLE 
  "BF"."BOOK_CATEGORY" 
ADD 
  CONSTRAINT "BOOK_CATEGORY_CATE2_NUM_FK" FOREIGN KEY ("CATE2_NUM") REFERENCES "BF"."SECOND_CATE" ("NUM") ENABLE;
ALTER TABLE 
  "BF"."BOOK_CATEGORY" 
ADD 
  CONSTRAINT "BOOK_CATEGORY_CATE3_NUM_FK" FOREIGN KEY ("CATE3_NUM") REFERENCES "BF"."THIRD_CATE" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOK_LIST
--------------------------------------------------------
ALTER TABLE 
  "BF"."BOOK_LIST" 
ADD 
  CONSTRAINT "BOOK_LIST_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ENABLE;
ALTER TABLE 
  "BF"."BOOK_LIST" 
ADD 
  CONSTRAINT "BOOK_LIST_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOKM
--------------------------------------------------------
ALTER TABLE 
  "BF"."BOOKM" 
ADD 
  CONSTRAINT "AUTHOR_NUM_FK" FOREIGN KEY ("AUTHOR_NUM") REFERENCES "BF"."AUTHOR" ("NUM") ENABLE;
ALTER TABLE 
  "BF"."BOOKM" 
ADD 
  CONSTRAINT "BOOKM_SERIES_NUM_FK" FOREIGN KEY ("SERIES_NUM") REFERENCES "BF"."SERIES" ("NUM") ENABLE;
ALTER TABLE 
  "BF"."BOOKM" 
ADD 
  CONSTRAINT "ILLUSTRATOR_NUM_FK" FOREIGN KEY ("ILLUSTRATOR_NUM") REFERENCES "BF"."AUTHOR" ("NUM") ENABLE;
ALTER TABLE 
  "BF"."BOOKM" 
ADD 
  CONSTRAINT "PUB_FK" FOREIGN KEY ("PUB_NUM") REFERENCES "BF"."PUBLISHER" ("PUB_NUM") ENABLE;
ALTER TABLE 
  "BF"."BOOKM" 
ADD 
  CONSTRAINT "TRANSLATOR_NUM_FK" FOREIGN KEY ("TRANSLATOR_NUM") REFERENCES "BF"."AUTHOR" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CART_WISH
--------------------------------------------------------
ALTER TABLE 
  "BF"."CART_WISH" 
ADD 
  CONSTRAINT "CART_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ON DELETE CASCADE ENABLE;
ALTER TABLE 
  "BF"."CART_WISH" 
ADD 
  CONSTRAINT "CART_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CASH_CHARGE
--------------------------------------------------------
ALTER TABLE 
  "BF"."CASH_CHARGE" 
ADD 
  CONSTRAINT "CASH_CHARGE_CHARGE_TYPE_NUM_FK" FOREIGN KEY ("CHARGE_TYPE_NUM") REFERENCES "BF"."CASH_CHARGE_TYPE" ("NUM") ENABLE;
ALTER TABLE 
  "BF"."CASH_CHARGE" 
ADD 
  CONSTRAINT "CASH_CHARGE_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE;
ALTER TABLE 
  "BF"."CASH_CHARGE" 
ADD 
  CONSTRAINT "CASH_CHARGE_POINT_NUM_FK" FOREIGN KEY ("POINT_NUM") REFERENCES "BF"."POINT" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KEYWORD_LIST
--------------------------------------------------------
ALTER TABLE 
  "BF"."KEYWORD_LIST" 
ADD 
  CONSTRAINT "KEYWORD_LIST_FK1" FOREIGN KEY ("KEYWORD_NUM") REFERENCES "BF"."KEYWORD" ("NUM") ON DELETE CASCADE ENABLE;
ALTER TABLE 
  "BF"."KEYWORD_LIST" 
ADD 
  CONSTRAINT "KEYWORD_LIST_FK2" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTICE
--------------------------------------------------------
ALTER TABLE 
  "BF"."NOTICE" 
ADD 
  CONSTRAINT "NOTICE_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT
--------------------------------------------------------
ALTER TABLE 
  "BF"."PAYMENT" 
ADD 
  CONSTRAINT "PAYMENT_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ENABLE;
ALTER TABLE 
  "BF"."PAYMENT" 
ADD 
  CONSTRAINT "PAYMENT_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POINT
--------------------------------------------------------
ALTER TABLE 
  "BF"."POINT" 
ADD 
  CONSTRAINT "POINT_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREFERENCE
--------------------------------------------------------
ALTER TABLE 
  "BF"."PREFERENCE" 
ADD 
  CONSTRAINT "PREFERENCE_AUTHOR_NUM_FK" FOREIGN KEY ("AUTHOR_NUM") REFERENCES "BF"."AUTHOR" ("NUM") ENABLE;
ALTER TABLE 
  "BF"."PREFERENCE" 
ADD 
  CONSTRAINT "PREFERENCE_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE;
ALTER TABLE 
  "BF"."PREFERENCE" 
ADD 
  CONSTRAINT "PREFERENCE_SERIES_NUM_FK" FOREIGN KEY ("SERIES_NUM") REFERENCES "BF"."SERIES" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QNA_CATE2
--------------------------------------------------------
ALTER TABLE 
  "BF"."QNA_CATE2" 
ADD 
  CONSTRAINT "QNA_CATE2_CATE1_NUM_FK" FOREIGN KEY ("CATE1_NUM") REFERENCES "BF"."QNA_CATE1" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECENT_LOOKBOOK
--------------------------------------------------------
ALTER TABLE 
  "BF"."RECENT_LOOKBOOK" 
ADD 
  CONSTRAINT "RECENT_LOOKBOOK_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ENABLE;
ALTER TABLE 
  "BF"."RECENT_LOOKBOOK" 
ADD 
  CONSTRAINT "RECENT_LOOKBOOK_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------
ALTER TABLE 
  "BF"."REVIEW" 
ADD 
  CONSTRAINT "REVIEW_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ON DELETE CASCADE ENABLE;
ALTER TABLE 
  "BF"."REVIEW" 
ADD 
  CONSTRAINT "REVIEW_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW_REPLY
--------------------------------------------------------
ALTER TABLE 
  "BF"."REVIEW_REPLY" 
ADD 
  CONSTRAINT "REVIE_REPLY_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE;
ALTER TABLE 
  "BF"."REVIEW_REPLY" 
ADD 
  CONSTRAINT "REVIE_REPLY_REVIEW_NUM_FK" FOREIGN KEY ("REVIEW_NUM") REFERENCES "BF"."REVIEW" ("NUM") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SECOND_CATE
--------------------------------------------------------
ALTER TABLE 
  "BF"."SECOND_CATE" 
ADD 
  CONSTRAINT "SECOND_CATE_FIRST_CATE_FK" FOREIGN KEY ("FIRST_CATE") REFERENCES "BF"."FIRST_CATE" ("NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table THIRD_CATE
--------------------------------------------------------
ALTER TABLE 
  "BF"."THIRD_CATE" 
ADD 
  CONSTRAINT "THIRD_CATE_SECOND_CATE_FK" FOREIGN KEY ("SECOND_CATE") REFERENCES "BF"."SECOND_CATE" ("NUM") ENABLE;


-- ----------------------------------------------------------------------------------------
-- Sequence
CREATE SEQUENCE  "BF"."AUTHOR_NUM_SEQ";
CREATE SEQUENCE  "BF"."BOOKM_NUM_SEQ";
CREATE SEQUENCE  "BF"."CASH_CHARGE_TYPE_NUM_SEQ";
CREATE SEQUENCE  "BF"."FIRST_CATE_SEQ";
CREATE SEQUENCE  "BF"."FREQUENCY_NUM_SEQ";
CREATE SEQUENCE  "BF"."MEMBER_NUM_SEQ";
CREATE SEQUENCE  "BF"."PUBLISHER_NUM_SEQ";
CREATE SEQUENCE  "BF"."REVIEW_NUM_SEQ";
CREATE SEQUENCE  "BF"."SECOND_CATE_SEQ";
CREATE SEQUENCE  "BF"."SERIES_NUM_SEQ";
CREATE SEQUENCE  "BF"."THIRD_CATE_SEQ";
CREATE SEQUENCE  "BF"."POINT_NUM_SEQ";
CREATE SEQUENCE  "BF"."RECENT_LOOKBOOK_NUM_SEQ";
CREATE SEQUENCE  "BF"."REVIEW_REPLY_NUM_SEQ";
CREATE SEQUENCE  "BF"."KEYWORD_NUM_SEQ";
CREATE SEQUENCE  "BF"."KEYWORD_LIST_NUM_SEQ";
CREATE SEQUENCE  "BF"."AUTHOREDIT_NUM_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE ;
 