-- 다음 순서대로 테이블을 삭제하면 의존관계에 걸리지 않고 모두 삭제 가능합니다. (생성시에는 반대 순서대로 하면 됩니다.)

DROP TABLE keyword_list;
DROP TABLE keyword;
DROP TABLE NOTICE;
-- NOTICE

DROP TABLE preference;
DROP TABLE recent_lookbook;
DROP TABLE book_list;
DROP TABLE cart_wish;

DROP TABLE book_category;
DROP TABLE event;
DROP TABLE example;
DROP TABLE third_cate;
DROP TABLE second_cate;
DROP TABLE first_cate;

DROP TABLE accuse;
DROP TABLE ACCUSE_CATE;
DROP TABLE review_reply;
DROP TABLE review;
DROP TABLE PAYMENT;
DROP TABLE bookm;
-- BOOKM DROP

DROP TABLE publisher;
DROP TABLE authoredit;
DROP TABLE author;
DROP TABLE country;
DROP TABLE series;
-- SERIES DROP

DROP TABLE BOOK_CONTACT;
DROP TABLE board_contact;
DROP TABLE BOARD_FREQUENCY;
DROP TABLE qna_cate2;
DROP TABLE qna_cate1;
-- QNA_CATE1 DROP

DROP TABLE cash_charge;
DROP TABLE cash_charge_type;
DROP TABLE CASH_CHARGE_MENU;
DROP TABLE point;
DROP TABLE MEMBER;
-- MEMBER DROP

DROP SEQUENCE  "BF"."AUTHOR_NUM_SEQ";
DROP SEQUENCE  "BF"."BOOKM_NUM_SEQ";
DROP SEQUENCE  "BF"."CASH_CHARGE_TYPE_NUM_SEQ";
DROP SEQUENCE  "BF"."FIRST_CATE_SEQ";
DROP SEQUENCE  "BF"."FREQUENCY_NUM_SEQ";
DROP SEQUENCE  "BF"."MEMBER_NUM_SEQ";
DROP SEQUENCE  "BF"."PUBLISHER_NUM_SEQ";
DROP SEQUENCE  "BF"."REVIEW_NUM_SEQ";
DROP SEQUENCE  "BF"."SECOND_CATE_SEQ";
DROP SEQUENCE  "BF"."SERIES_NUM_SEQ";
DROP SEQUENCE  "BF"."THIRD_CATE_SEQ";
DROP SEQUENCE  "BF"."POINT_NUM_SEQ";
DROP SEQUENCE  "BF"."RECENT_LOOKBOOK_NUM_SEQ";
DROP SEQUENCE  "BF"."REVIEW_REPLY_NUM_SEQ";
DROP SEQUENCE  "BF"."KEYWORD_NUM_SEQ";
DROP SEQUENCE  "BF"."KEYWORD_LIST_NUM_SEQ";
drop sequence "BF"."BOARD_CONTACT_NUM_SEQ";
drop sequence "BF"."BOARD_FREQUENCY_NUM_SEQ";
drop sequence "BF"."BOOK_CONTACT_NUM_SEQ";
drop sequence "BF"."CART_NUM_SEQ";
drop sequence "BF"."CASH_CHARGE_NUM_SEQ";
drop sequence "BF"."EVENT_NUM_SEQ";
drop sequence "BF"."EXAMPLE_NUM_SEQ";
drop sequence "BF"."NOTICE_NUM_SEQ";
drop sequence "BF"."PAYMENT_NUM_SEQ";
drop sequence "BF"."AUTHOREDIT_NUM_SEQ";

-- SEQUENCE