-- 다음 순서대로 생성하면 의존관계에 걸리지 않고 생성됩니다. (삭제시에는 반대 순서대로 하면 됩니다.)
CREATE TABLE "BF"."MEMBER"
(
    "NUM"             NUMBER(8,0),
    "ID"              VARCHAR2(40 CHAR) NOT NULL ENABLE,
    "PASSWORD"        VARCHAR2(40 CHAR) NOT NULL ENABLE,
    "EMAIL"           VARCHAR2(30 CHAR) NOT NULL ENABLE,
    "GENDER"          VARCHAR2(10 CHAR) NOT NULL ENABLE,
    "REGISTER_DATE"   DATE DEFAULT SYSDATE,
    "BIRTHDAY"        DATE NOT NULL ENABLE,
    "MARKETING_CHECK" VARCHAR2(5 CHAR),
    "IP"              VARCHAR2(40 CHAR),
    "LAST_JOIN"       DATE DEFAULT SYSDATE,
    "PHONE"           VARCHAR2(50 byte) NOT NULL ENABLE,
    "ROLE"            VARCHAR2(20 byte) DEFAULT 'ROLE_USER' NOT NULL ENABLE,
    "NAME" VARCHAR2(40 BYTE) NOT NULL ENABLE,
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    UNIQUE ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."POINT"
(
    "NUM"          NUMBER(8,0),
    "ID"           VARCHAR2(40 CHAR),
    "POINT"        NUMBER(8,0) NOT NULL ENABLE,
    "POINT_TYPE"   VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CHARGE_DATE"  DATE DEFAULT SYSDATE,
    "DESTORY_DATE" DATE DEFAULT SYSDATE+30,
    "STATE"        VARCHAR2(30 CHAR),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "POINT_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."CASH_CHARGE_TYPE"
(
    "NUM"         NUMBER(8,0),
    "CHARGE_TYPE" VARCHAR2(40 CHAR) NOT NULL ENABLE,
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;

CREATE TABLE "BF"."CASH_CHARGE_MENU" 
(
	"NUM" NUMBER(8,0), 
	"ID" NUMBER(8,0) NOT NULL ENABLE, 
	"CHARGE_CASH" NUMBER(8,0) NOT NULL ENABLE, 
	"PERCENTAGE" NUMBER(4,0) NOT NULL ENABLE, 
	PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS"  ENABLE, 
	UNIQUE ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS"  ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
	INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
)
TABLESPACE "USERS" ;
  
CREATE TABLE "BF"."CASH_CHARGE"
(
    "NUM"             NUMBER(8,0),
    "ID"              VARCHAR2(40 CHAR),
    "CHARGE_CASH"     NUMBER(8,0) NOT NULL ENABLE,
    "POINT_NUM"       NUMBER(8,0),
    "CHARGE_TYPE_NUM" NUMBER(8,0),
    "CHARGE_DATE"     DATE DEFAULT SYSDATE,
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "CASH_CHARGE_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE,
    CONSTRAINT "CASH_CHARGE_CHARGE_TYPE_NUM_FK" FOREIGN KEY ("CHARGE_TYPE_NUM") REFERENCES "BF"."CASH_CHARGE_TYPE" ("NUM") ENABLE,
    CONSTRAINT "CASH_CHARGE_POINT_NUM_FK" FOREIGN KEY ("POINT_NUM") REFERENCES "BF"."POINT" ("NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."QNA_CATE1"
(
    "NUM"  NUMBER(8,0),
    "NAME" VARCHAR2(40 CHAR) NOT NULL ENABLE,
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."QNA_CATE2"
(
    "NUM"       NUMBER(8,0),
    "NAME"      VARCHAR2(40 CHAR) NOT NULL ENABLE,
    "CATE1_NUM" NUMBER(8,0),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "QNA_CATE2_CATE1_NUM_FK" FOREIGN KEY ("CATE1_NUM") REFERENCES "BF"."QNA_CATE1" ("NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."BOARD_FREQUENCY"
(
    "NUM"        NUMBER(8,0),
    "TITLE"      VARCHAR2(40 CHAR) NOT NULL ENABLE,
    "CATEGORY"   NUMBER(8,0),
    "CONTENT"    VARCHAR2(2000 CHAR) NOT NULL ENABLE,
    "WRITE_DATE" DATE DEFAULT SYSDATE,
    "FILE_NAME"  VARCHAR2(100 CHAR),
    "FILE_SIZE"  NUMBER(8,0),
    "FILE_PATH"  VARCHAR2(200 CHAR),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "BOARD_FREQUENCY_CATEGORY_FK" FOREIGN KEY ("CATEGORY") REFERENCES "BF"."QNA_CATE2" ("NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."BOARD_CONTACT"
(
    "NUM"           NUMBER(8,0),
    "TITLE"         VARCHAR2(50 CHAR) NOT NULL ENABLE,
    "CONTENT"       VARCHAR2(2000 CHAR) NOT NULL ENABLE,
    "ID"            VARCHAR2(40 CHAR),
    "WRITE_DATE"    DATE,
    "CATEGORY"      NUMBER(8,0),
    "REPLY_CONTENT" VARCHAR2(2000 CHAR),
    "REPLY_CHECK"   VARCHAR2(10 CHAR),
    "FILE_NAME"     VARCHAR2(100 CHAR),
    "FILE_SIZE"     NUMBER(8,0),
    "FILE_PATH"     VARCHAR2(200 CHAR),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "BOARD_CONTACT_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE,
    CONSTRAINT "BOARD_CONTACT_CATEGORY_FK" FOREIGN KEY ("CATEGORY") REFERENCES "BF"."QNA_CATE2" ("NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."SERIES"
(
    "NUM"  NUMBER(8,0),
    "NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE,
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."COUNTRY"
(
    "COUNTRY_NUM"  VARCHAR2(4 byte),
    "COUNTRY_NAME" VARCHAR2(50 byte) NOT NULL ENABLE,
    "COUNTRY_EN"   VARCHAR2(50 byte) NOT NULL ENABLE,
    PRIMARY KEY ("COUNTRY_NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."AUTHOR"
(
    "NUM"         NUMBER(8,0),
    "NAME"        VARCHAR2(100 CHAR) NOT NULL ENABLE,
    "COUNTRY_NUM" VARCHAR2(4 byte) NOT NULL ENABLE,
    "BIRTHDAY"    VARCHAR2(2000 CHAR),
    "EDUCATION"   VARCHAR2(2000 byte),
    "CAREER"      VARCHAR2(2000 byte),
    "DEBUT"       VARCHAR2(2000 CHAR),
    "LINK"        VARCHAR2(2000 CHAR),
    "UPDATE_DATE" DATE NOT NULL ENABLE,
    "AWARDS"      VARCHAR2(3000 CHAR),
    "DESCRIBE" CLOB,
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "COUNTRY_NUM_FK" FOREIGN KEY ("COUNTRY_NUM") REFERENCES "BF"."COUNTRY" ("COUNTRY_NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" lob ("DESCRIBE") store AS
(
    TABLESPACE "USERS" ENABLE STORAGE IN ROW chunk 8192 pctversion 10 NOCACHE logging STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT)
) ;
  
  
CREATE TABLE "BF"."AUTHOREDIT"
(
    "NUM"        NUMBER(8,0),
    "AUTHOR_NUM" NUMBER(8,0),
    "CONTENT"    VARCHAR2(4000 byte),
    "CONDITION"  VARCHAR2(100 byte),
    "WRITE_DATE" DATE,
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "AUTHOREDIT_AUTHOR_NUM_FK" FOREIGN KEY ("AUTHOR_NUM") REFERENCES "BF"."AUTHOR" ("NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."PUBLISHER"
(
    "PUB_NUM"   NUMBER(8,0),
    "NAME"      VARCHAR2(50 byte) NOT NULL ENABLE,
    "URL"       VARCHAR2(100 byte),
    "JOIN_DATE" DATE,
    PRIMARY KEY ("PUB_NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."BOOKM"
(
    "BOOK_NUM"        NUMBER(8,0),
    "NAME"            VARCHAR2(100 CHAR) NOT NULL DISABLE,
    "WRITE_DATE"      VARCHAR2(1000 byte) NOT NULL DISABLE,
    "PUB_NUM"         NUMBER(8,0),
    "AUTHOR_NUM"      NUMBER(8,0),
    "ILLUSTRATOR_NUM" NUMBER(8,0),
    "TRANSLATOR_NUM"  NUMBER(8,0),
    "PRICE"           NUMBER(8,0) NOT NULL DISABLE,
    "SUPPORT"         VARCHAR2(100 byte),
    "IMG_PATH"        VARCHAR2(200 byte),
    "FILE_PATH"       VARCHAR2(200 byte),
    "FILE_NAME"       VARCHAR2(100 byte),
    "FILE_SIZE"       NUMBER(8,0),
    "PREFERENCE"      NUMBER(8,0),
    "SERIES_NUM"      NUMBER(8,0),
    "SUB_TITLE"       VARCHAR2(2000 CHAR),
    "DISCOUNT"        NUMBER(4,2),
    "DISCOUNT2"       NUMBER(4,2),
    "TYPE"            VARCHAR2(200 byte),
    "INTRO" CLOB,
    "PUB_INTRO" CLOB,
    "RENTAL_PERIOD" VARCHAR2(200 byte),
    "RENTAL_PRICE"  NUMBER(8,0),
    PRIMARY KEY ("BOOK_NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "PUB_FK" FOREIGN KEY ("PUB_NUM") REFERENCES "BF"."PUBLISHER" ("PUB_NUM") ENABLE,
    CONSTRAINT "AUTHOR_NUM_FK" FOREIGN KEY ("AUTHOR_NUM") REFERENCES "BF"."AUTHOR" ("NUM") ENABLE,
    CONSTRAINT "ILLUSTRATOR_NUM_FK" FOREIGN KEY ("ILLUSTRATOR_NUM") REFERENCES "BF"."AUTHOR" ("NUM") ENABLE,
    CONSTRAINT "TRANSLATOR_NUM_FK" FOREIGN KEY ("TRANSLATOR_NUM") REFERENCES "BF"."AUTHOR" ("NUM") ENABLE,
    CONSTRAINT "BOOKM_SERIES_NUM_FK" FOREIGN KEY ("SERIES_NUM") REFERENCES "BF"."SERIES" ("NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" lob ("INTRO") store AS
(
	TABLESPACE "USERS" ENABLE STORAGE IN ROW chunk 8192 pctversion 10 NOCACHE logging STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT)
)
lob ("PUB_INTRO") store AS
(
    TABLESPACE "USERS" ENABLE STORAGE IN ROW chunk 8192 pctversion 10 NOCACHE logging STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT)
) ;
  
  
CREATE TABLE "BF"."PAYMENT"
(
    "NUM"           NUMBER(8,0),
    "ORDER_NUM"     NUMBER(16,0) NOT NULL ENABLE,
    "BOOK_NUM"      NUMBER(8,0),
    "PRICE"         NUMBER(8,0) NOT NULL ENABLE,
    "PAYMENT_DATE"  DATE NOT NULL ENABLE,
    "PRESENT_CHECK" VARCHAR2(5 byte),
    "CANCEL_CHECK"  VARCHAR2(5 byte),
    "FREE_PASS"     VARCHAR2(5 byte),
    "ID"            VARCHAR2(40 CHAR),
    "PAY_TYPE"      VARCHAR2(50 byte),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "PAYMENT_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ENABLE,
    CONSTRAINT "PAYMENT_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."REVIEW"
(
    "NUM"        NUMBER(8,0),
    "ID"         VARCHAR2(40 CHAR),
    "BOOK_NUM"   NUMBER(8,0),
    "CONTENT"    VARCHAR2(4000 byte),
    "WRITE_DATE" DATE DEFAULT SYSDATE,
    "STAR_POINT" NUMBER(3,0) NOT NULL ENABLE,
    "SPOILER"    VARCHAR2(20 CHAR) NOT NULL ENABLE,
    "PREFERENCE" NUMBER(8,0) DEFAULT 0,
    "DISPLAY"    VARCHAR2(20 CHAR),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "REVIEW_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE,
    CONSTRAINT "REVIEW_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."REVIEW_REPLY"
(
    "NUM"        NUMBER(8,0),
    "ID"         VARCHAR2(40 CHAR),
    "CONTENT"    VARCHAR2(4000 byte),
    "WRITE_DATE" DATE DEFAULT SYSDATE,
    "REVIEW_NUM" NUMBER(8,0),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "REVIE_REPLY_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE,
    CONSTRAINT "REVIE_REPLY_REVIEW_NUM_FK" FOREIGN KEY ("REVIEW_NUM") REFERENCES "BF"."REVIEW" ("NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."ACCUSE_CATE"
(
    "NUM"         NUMBER(8,0),
    "DESCRIPTION" VARCHAR2(40 CHAR) NOT NULL ENABLE,
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;

  
CREATE TABLE "BF"."ACCUSE"
(
    "NUM"        NUMBER(8,0),
    "ID"         VARCHAR2(40 CHAR),
    "ACCUSE_NUM" NUMBER(8,0),
    "REVIEW_NUM" NUMBER(8,0),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "ACCUSE_ACCUSE_NUM_FK" FOREIGN KEY ("ACCUSE_NUM") REFERENCES "BF"."ACCUSE_CATE" ("NUM") ENABLE,
    CONSTRAINT "REVIEW_REVIEW_NUM_FK" FOREIGN KEY ("REVIEW_NUM") REFERENCES "BF"."REVIEW" ("NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."FIRST_CATE"
(
    "NUM"  NUMBER(4,0),
    "NAME" VARCHAR2(40 byte) NOT NULL ENABLE,
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."SECOND_CATE"
(
    "NUM"        NUMBER(4,0),
    "NAME"       VARCHAR2(40 byte) NOT NULL ENABLE,
    "FIRST_CATE" NUMBER(4,0),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "SECOND_CATE_FIRST_CATE_FK" FOREIGN KEY ("FIRST_CATE") REFERENCES "BF"."FIRST_CATE" ("NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."THIRD_CATE"
(
    "NUM"         NUMBER(4,0),
    "NAME"        VARCHAR2(40 byte) NOT NULL ENABLE,
    "SECOND_CATE" NUMBER(4,0),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "THIRD_CATE_SECOND_CATE_FK" FOREIGN KEY ("SECOND_CATE") REFERENCES "BF"."SECOND_CATE" ("NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."BOOK_CATEGORY"
(
    "NUM"       NUMBER(8,0),
    "BOOK_NUM"  NUMBER(8,0) NOT NULL ENABLE,
    "CATE1_NUM" NUMBER(4,0),
    "CATE2_NUM" NUMBER(4,0),
    "CATE3_NUM" NUMBER(4,0),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "BOOK_CATEGORY_CATE1_NUM_FK" FOREIGN KEY ("CATE1_NUM") REFERENCES "BF"."FIRST_CATE" ("NUM") ENABLE,
    CONSTRAINT "BOOK_CATEGORY_CATE2_NUM_FK" FOREIGN KEY ("CATE2_NUM") REFERENCES "BF"."SECOND_CATE" ("NUM") ENABLE,
    CONSTRAINT "BOOK_CATEGORY_CATE3_NUM_FK" FOREIGN KEY ("CATE3_NUM") REFERENCES "BF"."THIRD_CATE" ("NUM") ENABLE,
    CONSTRAINT "BOOK_CATEGORY_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ON
  DELETE CASCADE ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."WISHLIST"
(
    "NUM"      NUMBER(8,0),
    "ID"       VARCHAR2(40 CHAR),
    "BOOK_NUM" NUMBER(8,0),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "WISHLIST_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ENABLE,
    CONSTRAINT "WISHLIST_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."CART"
(
    "NUM"      NUMBER(8,0),
    "ID"       VARCHAR2(40 CHAR),
    "BOOK_NUM" NUMBER(8,0),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "CART_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ENABLE,
    CONSTRAINT "CART_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."BOOK_LIST"
(
    "NUM"      NUMBER(8,0),
    "ID"       VARCHAR2(40 CHAR),
    "BOOK_NUM" NUMBER(8,0),
    "PAY_DATE" DATE,
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "BOOK_LIST_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ENABLE,
    CONSTRAINT "BOOK_LIST_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;
  
  
CREATE TABLE "BF"."RECENT_LOOKBOOK"
(
    "NUM"          NUMBER(8,0),
    "ID"           VARCHAR2(40 CHAR),
    "BOOK_NUM"     NUMBER(8,0),
    "LOOK_DATE"    DATE DEFAULT SYSDATE,
    "DESTROY_DATE" DATE DEFAULT SYSDATE+14,
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "RECENT_LOOKBOOK_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE,
    CONSTRAINT "RECENT_LOOKBOOK_BOOK_NUM_FK" FOREIGN KEY ("BOOK_NUM") REFERENCES "BF"."BOOKM" ("BOOK_NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;


CREATE TABLE "BF"."PREFERENCE"
(
    "NUM"        NUMBER(8,0),
    "ID"         VARCHAR2(40 CHAR),
    "AUTHOR_NUM" NUMBER(8,0),
    "SERIES_NUM" NUMBER(8,0),
    PRIMARY KEY ("NUM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 compute STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT) TABLESPACE "USERS" ENABLE,
    CONSTRAINT "PREFERENCE_AUTHOR_NUM_FK" FOREIGN KEY ("AUTHOR_NUM") REFERENCES "BF"."AUTHOR" ("NUM") ENABLE,
    CONSTRAINT "PREFERENCE_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE,
    CONSTRAINT "PREFERENCE_SERIES_NUM_FK" FOREIGN KEY ("SERIES_NUM") REFERENCES "BF"."SERIES" ("NUM") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS logging STORAGE
(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 buffer_pool DEFAULT
)
TABLESPACE "USERS" ;

CREATE TABLE "BF"."NOTICE" 
(	"NUM" NUMBER(8,0), 
	"ID" VARCHAR2(40 CHAR), 
	"TITLE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"WRITE_DATE" DATE DEFAULT SYSDATE, 
	PRIMARY KEY ("NUM")
	USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "USERS"  ENABLE, 
	CONSTRAINT "NOTICE_ID_FK" FOREIGN KEY ("ID") REFERENCES "BF"."MEMBER" ("ID") ENABLE
)
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
(
	INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
)
TABLESPACE "USERS" ;

-- ----------------------------------------------------------------------------------------
-- Sequence
CREATE SEQUENCE  "BF"."AUTHOR_NUM_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BF"."BOOKM_NUM_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BF"."CASH_CHARGE_TYPE_NUM_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BF"."FIRST_CATE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BF"."FREQUENCY_NUM_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BF"."MEMBER_NUM_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BF"."PUBLISHER_NUM_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BF"."REVIEW_NUM_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BF"."SECOND_CATE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BF"."SERIES_NUM_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BF"."THIRD_CATE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
